### ISSUE TITLE
Issue with Dell r730xd

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#1]
I'm seeing an issue using badfish on the Dell r730xd running `2.60.60.60` firmware.

```
FAIL: POST command failed to create BIOS config job, status code is 503
```

**Comment by grafuls** [comment]
This error message appears when trying to create a job if there is a pending job on the rac queue.
This issue has been addressed on https://github.com/redhat-performance/badfish/commit/662a4a1271ceeaa5a6cd6ea0f48cbc147f2b4af2.
Added logic to check and clear the job queue if there are pending jobs before creating the BIOS config job.
