### ISSUE TITLE
[RFE] Power on and off capabilities

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/badfish#10]
Add the ability to power on or off a remote host.

**Comment by bengland2** [comment]
would be nice to be able to also do a soft reset, instead of power cycle.  This is different than --reboot-only option, which requires the operating system to cooperate.   soft reset forces BIOS to reboot, but does not take the drastic step of shutting off power then restoring it, which could possibly put more stress on hardware components.   Also, when I requested --reboot-only, it didn't work anyway:

```
root@e26-h01-740xd dblack-method]# ./badfish.sh --reboot-only
podman run -it --rm --volume /root/badfish:/badfish:z,ro quads/badfish -u quads -p 502328 -i /badfish/config/idrac_interfaces.yml -H mgmt-e26-h03-740xd --reboot-only
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- ERROR    - Command failed to GracefulRestart server, status code is: 400.
- WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
podman run -it --rm --volume /root/badfish:/badfish:z,ro quads/badfish -u quads -p 502328 -i /badfish/config/idrac_interfaces.yml -H mgmt-e26-h05-740xd --reboot-only
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- ERROR    - Command failed to GracefulRestart server, status code is: 400.
- WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
podman run -it --rm --volume /root/badfish:/badfish:z,ro quads/badfish -u quads -p 502328 -i /badfish/config/idrac_interfaces.yml -H mgmt-e26-h07-740xd --reboot-only
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- ERROR    - Command failed to GracefulRestart server, status code is: 400.
- WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
```

**Comment by grafuls** [comment]
> would be nice to be able to also do a soft reset, instead of power cycle. This is different than --reboot-only option, which requires the operating system to cooperate. soft reset forces BIOS to reboot, but does not take the drastic step of shutting off power then restoring it, which could possibly put more stress on hardware components. Also, when I requested --reboot-only, it didn't work anyway:
> 
> ```
> root@e26-h01-740xd dblack-method]# ./badfish.sh --reboot-only
> podman run -it --rm --volume /root/badfish:/badfish:z,ro quads/badfish -u quads -p 502328 -i /badfish/config/idrac_interfaces.yml -H mgmt-e26-h03-740xd --reboot-only
> - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
> - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
> - ERROR    - Command failed to GracefulRestart server, status code is: 400.
> - WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
> podman run -it --rm --volume /root/badfish:/badfish:z,ro quads/badfish -u quads -p 502328 -i /badfish/config/idrac_interfaces.yml -H mgmt-e26-h05-740xd --reboot-only
> - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
> - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
> - ERROR    - Command failed to GracefulRestart server, status code is: 400.
> - WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
> podman run -it --rm --volume /root/badfish:/badfish:z,ro quads/badfish -u quads -p 502328 -i /badfish/config/idrac_interfaces.yml -H mgmt-e26-h07-740xd --reboot-only
> - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
> - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
> - ERROR    - Command failed to GracefulRestart server, status code is: 400.
> - WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
> ```

This is an issue with the ResetType that needs to be resolved for newer models.
@bengland2 you can try using the already existing `--racreset` option which does an iDRAC reset or also we have `--power-cycle` option which will send a `ForceOff` instruction to the host and an subsequent power `On` instruction.

**Comment by grafuls** [comment]
Power on and off capabilities have already been added on a previous patch.
https://github.com/redhat-performance/badfish/#power-state-control
