### ISSUE TITLE
Provide a way to input a list of hosts on which to operate

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#11]
This is an RFE to provide feeding badfish a list of hosts to operate upon.

e.g.

```
./badfish.py -l hosts.txt  -u root -p yourpass -i config/idrac_interfaces.yml -t foreman --pxe
```

This will be useful for scale/perf tenants to operate on their hosts en-masse without having to use a `for loop` and sequential operation.  The `async` library would be pretty sweet for this as Gonza stated.

**Comment by grafuls** [comment]
Fixed on: https://github.com/redhat-performance/badfish/pull/13
