### ISSUE TITLE
changing boot order mysteriously fails in badfish in Alias run from JetSki

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/badfish#119]
**Your System Details**

Alias cloud 10 
e24-h19-740xd is deployer
e24-h{29,31,33}-740xd are masters

* Python Version:

[kni@e24-h19-740xd ~]$ python3 --version
Python 3.6.8

* Operating System:

RHEL 8.1 Linux e24-h19-740xd.alias.bos.scalelab.redhat.com 4.18.0-147.el8.x86_64 

* Target System Type: (_e.g. Dell, SuperMicro_)

Dell

* IPMI / Out-of-band Firmware Version: (_e.g. iDRAC 8 2.60.60.60)

I dunno

**Describe the bug**

badfish fails to do "-t director" boot order, see jetski playbook log here, task is: Set nodes to director boot order:

http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/ocp4/jetski/jetski.08101636.log

**To Reproduce / What were you Doing?**
1. run JetSki in Alias cluster as documented, see config files in above URL's directory:
2. See error described above.

However, when I run -t director command as follows, it works:

https://pastebin.com/hrpDXm6M

**Expected Behavior**

If badfish fails, we should get a better indication of what's wrong than:

- ERROR    - Failed to communicate with mgmt-e24-h29-740xd.alias.bos.scalelab.redhat.com
- ERROR    - There was something wrong executing Badfish.

It appears that the problems JetSki has in Alias lab may stem from this.  @smalleni  ?

**Comment by bengland2** [comment]
@QuantumPosix FYI

**Comment by bengland2** [comment]
I'm still seeing an issue with badfish not changing boot order on e25-h25-740xd in cloud17 right now, running latest master branch of badfish from latest Fedora 31.
```
[bengland@localhost badfish]$ ~/badfish/src/badfish/badfish.py -u quads -p bos@184 -H mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com -i ~/badfish/config/idrac_interfaces.yml -t director
- INFO     - Job queue for iDRAC mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com successfully cleared.
- WARNING  - Some interfaces are not valid boot devices. Ignoring: NIC.Integrated.1-2-1
- WARNING  - No changes were made since the boot order already matches the requested.
- ERROR    - POST command failed to create BIOS config job, status code is 400.
- WARNING  - No pending data present to create a Configuration job.
- ERROR    - There was something wrong executing Badfish.
```
The warning about some interfaces not valid boot devices seems wrong.  It should remove any interfaces that aren't valid boot devices, yes?   

If the "boot order already matches the requested", then how come it tried to do more?   

Why did the POST command fail?   Why was it executed?

@grafuls  ?

**Comment by grafuls** [comment]
> I'm still seeing an issue with badfish not changing boot order on e25-h25-740xd in cloud17 right now, running latest master branch of badfish from latest Fedora 31.
> 
> ```
> [bengland@localhost badfish]$ ~/badfish/src/badfish/badfish.py -u quads -p bos@184 -H mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com -i ~/badfish/config/idrac_interfaces.yml -t director
> - INFO     - Job queue for iDRAC mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com successfully cleared.
> - WARNING  - Some interfaces are not valid boot devices. Ignoring: NIC.Integrated.1-2-1
> - WARNING  - No changes were made since the boot order already matches the requested.
> - ERROR    - POST command failed to create BIOS config job, status code is 400.
> - WARNING  - No pending data present to create a Configuration job.
> - ERROR    - There was something wrong executing Badfish.
> ```
> 
> The warning about some interfaces not valid boot devices seems wrong. It should remove any interfaces that aren't valid boot devices, yes?
> 
> If the "boot order already matches the requested", then how come it tried to do more?
> 
> Why did the POST command fail? Why was it executed?
> 
> @grafuls ?

Hi @bengland2, yday we pushed some fixes to a bug we discovered earlier this week regarding changing boot order.
I have tested this against another 740 in alias and it seems to be working as expected:
```
> src/badfish/badfish.py -H mgmt-740xd.redhat.com -u root -p {PASS} -t foreman -i config/idrac_interfaces.yml
- INFO     - Job queue for iDRAC mgmt-740xd.redhat.com successfully cleared.
- INFO     - PATCH command passed to update boot order.
- INFO     - POST command passed to create target config job.
- INFO     - Command passed to ForceOff server, code return is 204.
- INFO     - Polling for host state: Not Down
- POLLING: [------------------->] 100% - Host state: On  
- INFO     - Command passed to On server, code return is 204.
> src/badfish/badfish.py -H mgmt-740xd.redhat.com -u root -p {PASS} --check-boot -i config/idrac_interfaces.yml
- WARNING  - Current boot order is set to: foreman.
> src/badfish/badfish.py -H mgmt-740xd.redhat.com -u root -p {PASS} -t foreman -i config/idrac_interfaces.yml  
- WARNING  - No changes were made since the boot order already matches the requested.
```

**Comment by grafuls** [comment]
> Hi,
> Any update on this issue as I'm facing a same issue in scalelab for R630's in cloud05.
> http://paste.openstack.org/show/797025/

Hi @asyedham,
This issue is related to having a pending configuration job on the lifecycle controller. You can workaround this by resetting idrac via BF `--racreset` and subsequent `--power-cycle` or you can also try to run `--clear-jobs`.
If this is from within the automation I would suggest you include this steps before trying to execute any configuration changes like boot order.

**Comment by bengland2** [comment]
@grafuls @smalleni this did not work, here's what happens when I try it, I did git pull right beforehand.   JetSki does not proceed because of these errors.

```
[root@localhost badfish]# src/badfish/badfish.py -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h29-740xd.alias.bos.scalelab.redhat.com --check-boot
- WARNING  - Current boot order does not match any of the given.
- INFO     - Current boot order:
- INFO     - 1: HardDisk.List.1-1
- INFO     - 2: NIC.Integrated.1-1-1
- INFO     - 3: NIC.Integrated.1-2-1
- INFO     - 4: NIC.Slot.7-2-1
- INFO     - 5: NIC.Slot.7-1-1
- INFO     - 6: NIC.Integrated.1-3-1
- INFO     - 7: NIC.Integrated.1-4-1

[root@localhost badfish]# src/badfish/badfish.py -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h29-740xd.alias.bos.scalelab.redhat.com -t director
- INFO     - Job queue for iDRAC mgmt-e25-h29-740xd.alias.bos.scalelab.redhat.com successfully cleared.
- INFO     - PATCH command passed to update boot order.
- INFO     - POST command passed to create target config job.
- ERROR    - There was something wrong executing Badfish.
```
similarly on e25-h25:
```
[root@localhost badfish]# src/badfish/badfish.py -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com --check-boot
- WARNING  - Current boot order does not match any of the given.
- INFO     - Current boot order:
- INFO     - 1: NIC.Integrated.1-1-1
- INFO     - 2: NIC.Slot.7-2-1
- INFO     - 3: NIC.Slot.7-1-1
- INFO     - 4: NIC.Integrated.1-3-1
- INFO     - 5: HardDisk.List.1-1
- INFO     - 6: NIC.Integrated.1-4-1
[root@localhost badfish]# src/badfish/badfish.py -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com -t director
- WARNING  - Job queue already cleared for iDRAC mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com, DELETE command will not execute.
- WARNING  - Some interfaces are not valid boot devices. Ignoring: NIC.Integrated.1-2-1
- WARNING  - No changes were made since the boot order already matches the requested.
- ERROR    - POST command failed to create BIOS config job, status code is 400.
- WARNING  - No pending data present to create a Configuration job.
- ERROR    - There was something wrong executing Badfish.
```

however with e25-h27, no problems:
```
[root@localhost badfish]# src/badfish/badfish.py -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h27-740xd.alias.bos.scalelab.redhat.com -t director
- WARNING  - No changes were made since the boot order already matches the requested.
[root@localhost badfish]# src/badfish/badfish.py -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h27-740xd.alias.bos.scalelab.redhat.com --check-boot
- WARNING  - Current boot order is set to: director.
```

Here's the JetSki deployment that failed because of this problem (not its fault), including the ansible-playbook log:

http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/ocp4/alias-cloud17-2020-10-07/

I am attempting to work around this by manually changing the BIOS boot order in the iDRAC web GUI, where I have privs.   If you want to try something let me know and I'll step aside.

**Comment by smalleni** [comment]
@bengland2 For now, if you are able to manually set boot order, I would suggest kicking off JetSki with --skip-tags=bootorder so it doesn't attempt to do it again. I will defer to @grafuls to fix the actual badfish issue.

**Comment by bengland2** [comment]
@grafuls @smalleni on e25-h25-740xd, the thing that caused the problem was that NIC.Integrated.1-2-1 was not enabled for PXE boot in the BIOS.  So badfish can't include this in the boot order.   Kambiz helped me out and fixed this (I didn't have privs), and now badfish seems to be working ok to set the boot order on e25-h25-740xd to -t director.
```
[root@localhost badfish]# src/badfish/badfish.py -vv -u quads -p bos@184 -i config/idrac_interfaces.yml -H mgmt-e25-h25-740xd.alias.bos.scalelab.redhat.com --check-boot
- DEBUG    - Systems service: /redfish/v1/Systems/System.Embedded.1.
- DEBUG    - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- DEBUG    - Getting bios boot mode.
- WARNING  - Current boot order is set to: director.
```
shouldn't the lab team make sure that all the servers in Alias are set up with the right interfaces enabled so that badfish can work?   Perhaps a script could be run to check this?

**Comment by bengland2** [comment]
Kambiz helped me out by enabling this interface and now badfish works on it and so does JetSki.    At least there was an error message in badfish that let me figure out what was going wrong:
```
Some interfaces are not valid boot devices. Ignoring: NIC.Integrated.1-2-1
```
