### ISSUE TITLE
[RFE] Implement unmounting of ISO images

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#125]
There might be some interest to both mount and unmount ISO images via the RedFish API, certainly at least removal of any mounted ISO images is already warranted in our own R&D usage.

For now let's implement checking and unmounting any virtual media / ISOs as a baseline check for validation and this can be expanded upon later to support mounting actual virtual media / ISO if there is demand.

Something like the following might be what we want initially:

```
badfish --check-iso
```

```
badfish --unmount-iso
```

We can extend this further to provide an ISO host and image file if it's useful.

This seems to be supported on SuperMicro here:

https://www.supermicro.com/manuals/other/RedfishRefGuide.pdf

```
/redfish/v1/Managers/1/VM1/CfgCD/Actions/IsoConfig.UnMount
```

```
7.24.2 Verify whether the ISO is mounted from Redfish command
URL: ${BMC_IP}/redfish/v1/Managers/1/VirtualMedia/CD[mounted_dev_num]
Method supported: Get
Body: LEAVE_IT_EMPTY
```

```
7.24.3 Unmount the ISO
URL:
${BMC_IP}/redfish/v1/Managers/1/VirtualMedia/CD[mounted_dev_num]/Actions/VirtualMedia.Eje
ctMedia
Method supported: Post
Body: {}
```

I'm still poking around for Dell redfish endpoint references but we should do the same thing there.

**Comment by grafuls** [comment]
For Dell we are capable of listing the existing VirtualMedia and the Inserted value but there is no endpoint for unmounting these. We might still want to add the functionality and display a warning msg when trying to run the unmount command against a Dell.
Also started by modifying the check argument to `--check-virtual-media`.
We could also be able to pass as an argument which VirtualMedia device we want to unmount.
