### ISSUE TITLE
no support for AMD servers in Alias lab

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/badfish#147]
**Your System Details**

Alias cloud12 consisting of e20-{h25,h27}-7425 and e20-{h29,h31}-7525  

* Python Version: Python 3.6.8 
* Operating System: Centos 8.2.2004
* Target System Type: (_e.g. Dell, SuperMicro_)  Dell AMD 7425, AMD 7525
* IPMI / Out-of-band Firmware Version: (_e.g. iDRAC 8 2.60.60.60)

IDRAC 4.22.00.00
BIOS 1.13.4

**Describe the bug**

need AMD server support for Alias lab

**To Reproduce / What were you Doing?**

run command below.

**Expected Behavior**

badfish works out of the box with AMD servers

**Logs / Screenshots**

[root@localhost badfish]# src/badfish/badfish.py -H mgmt-e20-h27-7425.alias.bos.scalelab.redhat.com  -u quads -p bos@253 -i config/idrac_interfaces.yml --check-boot
- ERROR    - Couldn't find a valid key defined on the interfaces yaml: director_7425_interfaces
- ERROR    - There was something wrong executing Badfish

**Additional Details**

I'm having trouble figuring out what idrac_interfaces.yml should be, because the 7525 in particular looks a bit different than the 740xd.

**Comment by bengland2** [comment]
This at least lets me talk to the servers.   But not sure if the boot order is correct.
```
diff --git a/config/idrac_interfaces.yml b/config/idrac_interfaces.yml
index 06272fc..8d4c1cf 100644
--- a/config/idrac_interfaces.yml
+++ b/config/idrac_interfaces.yml
@@ -14,6 +14,8 @@ director_r720xd_interfaces: NIC.Slot.4-2-1,HardDisk.List.1-1,NIC.Integrated.1-3-
 director_r730xd_interfaces: NIC.Integrated.1-2-1,HardDisk.List.1-1,NIC.Integrated.1-3-1
 director_740xd_interfaces: NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.7-2-1,NIC.Slot.7-1-1,NIC.Integrated.1-3-1,HardDisk.List.1-1
 director_r930_interfaces: NIC.Integrated.1-2-1,HardDisk.List.1-1,NIC.Integrated.1-3-1
+director_7425_interfaces: NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.7-2-1,NIC.Slot.7-1-1,NIC.Integrated.1-3-1,HardDisk.List.1-1
+director_7525_interfaces: NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.6-1-1,NIC.Slot.6-2-1,NIC.Embedded.1-1-1,HardDisk.List.1-1
 foreman_r620_interfaces: NIC.Integrated.1-3-1,HardDisk.List.1-1,NIC.Slot.2-4,NIC.Slot.2-1,NIC.Slot.2-2,NIC.Slot.2-3
 foreman_r630_interfaces: NIC.Slot.2-1-1,HardDisk.List.1-1,NIC.Integrated.1-2-1
 foreman_fc640_b01_interfaces: NIC.Integrated.1-1-1,HardDisk.List.1-1,NIC.ChassisSlot.8-1-1
@@ -25,6 +27,8 @@ foreman_r720xd_interfaces: NIC.Integrated.1-3-1,HardDisk.List.1-1,NIC.Slot.4-2-1
 foreman_r730xd_interfaces: NIC.Integrated.1-3-1,HardDisk.List.1-1,NIC.Integrated.1-2-1
 foreman_740xd_interfaces: NIC.Integrated.1-3-1,NIC.Integrated.1-1-1,NIC.Slot.7-2-1,NIC.Slot.7-1-1,HardDisk.List.1-1,NIC.Integrated.1-2-1
 foreman_r930_interfaces: NIC.Integrated.1-3-1,HardDisk.List.1-1,NIC.Integrated.1-2-1
+foreman_7425_interfaces: NIC.Integrated.1-3-1,NIC.Integrated.1-1-1,NIC.Slot.7-2-1,NIC.Slot.7-1-1,HardDisk.List.1-1,NIC.Integrated.1-2-1
+foreman_7525_interfaces: NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.6-1-1,NIC.Slot.6-2-1,NIC.Embedded.1-1-1,HardDisk.List.1-1
```

**Comment by bengland2** [comment]
@QuantumPosix do you think this is correct?

**Comment by QuantumPosix** [comment]
I have the order listed for the following :
director_7425_interfaces:
NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.7-2-1,NIC.Slot.7-1-1,NIC.Integrated.1-3-1,HardDisk.List.1-1
director_7525_interfaces:
NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.6-1-1,NIC.Slot.6-2-1,NIC.Embedded.1-1-1,HardDisk.List.1-1
foreman_7425_interfaces:
NIC.Integrated.1-3-1,NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.7-2-1,NIC.Slot.7-1-1,HardDisk.List.1-1
foreman_7525_interfaces:
NIC.Embedded.1-1-1,NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.6-1-1,NIC.Slot.6-2-1,HardDisk.List.1-1
~ Thanks,

Chris

**Comment by bengland2** [comment]
see PR #149

**Comment by sadsfae** [comment]
Hey I think this is sorted now via https://github.com/redhat-performance/badfish/pull/153 if not or need adjustment just re-open.
