### ISSUE TITLE
[BUG] passing `--host` argument gets interpreted as `--host-list`

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/badfish#151]
**Your System Details**

* Python Version: Python 3.9.0
* Operating System: Fedora release 33
* Target System Type: ANY
* IPMI / Out-of-band Firmware Version: ANY

**Describe the bug**
Badfish argument for passing the host name only accepts `-H` which some people might guess that the analogue `--host` argument would also be accepted. Instead, BF interprets this as an incomplete call for `--host-list` and goes into trying to open a file on the current directory with the name of the hostname you are passing resulting in an error trying to read from `{HOSTNAME}`

**To Reproduce / What were you Doing?**
1. badfish.py --host mgmt-hostname.com -u root -p {PASS} --check-boot
2. See error:
[__main__] - ERROR    - There was something wrong reading from mgmt-hostname.com

**Expected Behavior**
BF executes the desired action

**Additional Details**
We might want to look into adding the `--host` definition for the `-H` argument as well as preventing argparse from "auto" completing the argument name.

**Comment by sadsfae** [comment]
+1 on turning off argparse autocomplete unless we have other stuff that relies on it, I don't think that's the case anywhere.
