### ISSUE TITLE
TypeError: shield() got an unexpected keyword argument 'loop' in latest quay.io/quads/badfish

### ISSUE THREAD

**Issue by mordechai** [redhat-performance/badfish#205]
Attempting to run badfish from podman in rdu2 lab.

**Describe the bug**

magnolia :: /tmp » /bin/python --version
Python 3.9.7

magnolia :: /tmp » podman pull quay.io/quads/badfish

Trying to pull quay.io/quads/badfish:latest...
Getting image source signatures
Copying blob ba51967de001 done  
Copying blob a0d0a0d46f8b done  
Copying blob 5429bbf61688 done  
Copying blob e57f56899fb2 done  
Copying blob c60d7396f087 done  
Copying blob 469e8efa9283 done  
Copying blob 15c3741996eb done  
Copying blob 401188f48cba done  
Copying blob 726b4596459a done  
Copying blob e3c3d190eb70 done  
Copying blob 96be150d610d done  
Copying config 87c2ddc5bb done  
Writing manifest to image destination
Storing signatures
87c2ddc5bb28c2635752014d29a97d887bed56a1945c1d195d18ed5f2d070aee
magnolia :: /tmp » ansible-ipi-install]# podman run -it --rm --dns xx quay.io/quads/badfish -u XX -p XX -i config/idrac_interfaces.yml -H mgmt-fxx.com
^C
magnolia :: /tmp » podman run -it --rm --dns XX quay.io/quads/badfish -u quads -p XX -i config/idrac_interfaces.yml -H mgmt-fxxcom --power-state 
Traceback (most recent call last):
  File "/usr/local/bin/badfish", line 11, in <module>
    load_entry_point('badfish==1.0.0', 'console_scripts', 'badfish')()
  File "/usr/local/lib/python3.10/site-packages/badfish-1.0.0-py3.10.egg/badfish/badfish.py", line 2175, in main
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/badfish-1.0.0-py3.10.egg/badfish/badfish.py", line 1830, in execute_badfish
  File "/usr/local/lib/python3.10/site-packages/badfish-1.0.0-py3.10.egg/badfish/badfish.py", line 40, in badfish_factory
  File "/usr/local/lib/python3.10/site-packages/badfish-1.0.0-py3.10.egg/badfish/badfish.py", line 70, in init
  File "/usr/local/lib/python3.10/site-packages/badfish-1.0.0-py3.10.egg/badfish/badfish.py", line 431, in validate_credentials
  File "/usr/local/lib/python3.10/site-packages/async_lru.py", line 237, in wrapped
    return (yield from asyncio.shield(fut, loop=_loop))
TypeError: shield() got an unexpected keyword argument 'loop'

**To Reproduce / What were you Doing?**
1. Pull latest badfish from quay.io
2. Attempt a power status command via podman using latest image

**Expected Behavior**
Badfish commands to work.

**Logs / Screenshots**

**Additional Details**
Seems the image on quay was recently updated

**Comment by grafuls** [comment]
Thanks for raising the issue Mordechai!
We've seen it yday and unfortunately it wasn't our changes but asyncio once more making non backwards compatible changes.
You can find this issue reported here: https://github.com/aio-libs/async-lru/issues/383

We have amended our dockerfiles to downgrade to at least python 3.9 as a workaround for the time being.
This has been addressed here: https://github.com/redhat-performance/badfish/pull/203
If you pull the image from quay.io once more you'd have a working container image.
Bare in mind if you are running through podman you need to include --dns if you are connected to the VPN and if you are running --screenshot you need to map a volume.

E.g.:
`podman run -it --rm -v /tmp:/badfish --dns {DNS IP} --security-opt label=disable quay.io/quads/badfish:development --host {OOB_MGMT} -u root -p {PASS} --screenshot`
