### ISSUE TITLE
Enhancements to One-Shot Boot

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#23]
This is an RFE for some of the things we've discussed recently:

- Allow a one-shot boot option that does not require the interface string itself like `--boot-to` does, where you can specify something like `foreman` or `director` that would map to an entry in `idrac_interfaces.yml`

e.g.

```
badfish.py -H mgmt-your-server.example.com -u root -p yourpass --boot-to foreman
```

- If an IPMI FQDN is used it will use this over the default entries for either `foreman` or `director`

e.g. if I had the following in `idrac_interfaces.yml` it would use that custom entry instead

```
foreman_mgmt-server.example.com_interfaces: NIC.Integrated.1-3-1,NIC.Integrated.1-2-1
```

This would help in cases where vendor boot interface orders may not always match across a common system type (hasn't happened to us yet but could be useful in other environments) or generally lets people set their own as needed.

**Comment by grafuls** [comment]
https://github.com/redhat-performance/badfish/pull/50/commits/09ecddc9cbb9503222aaeb4e6899c1cf19a8f434
