### ISSUE TITLE
Setting director-style interfaces fails

### ISSUE THREAD

**Issue by mkarg75** [redhat-performance/badfish#239]
**Your System Details**
not relevant

* Python Version:
Python 3.10.2

* Operating System:
Fedora 35
* Target System Type: (_e.g. Dell, SuperMicro_)
Dell fc640

* IPMI / Out-of-band Firmware Version: (_e.g. iDRAC 8 2.60.60.60)
Version 4.22.00.53(Build 03)

**Describe the bug**
Setting the director-style interface order on a fc-640 returns an error:
```
- ERROR    - Couldn't find a valid key defined on the interfaces yaml: uefi_fc640_b04_interfaces
```

**To Reproduce / What were you Doing?**
1. Clone the badfish repo
2. Run the command `src/badfish/badfish.py -u quads -p <redacted> -i config/idrac_interfaces.yml -H mgmt-e22-h12-b04-fc640.rdu2.scalelab.redhat.com -t director`
4. Check the output: `- ERROR    - Couldn't find a valid key defined on the interfaces yaml: uefi_fc640_b04_interfaces`

**Expected Behavior**
No error message and the interface order set to director-style

**Logs / Screenshots**
```
t14:/tmp/badfish$ git clone https://github.com/redhat-performance/badfish.git
Cloning into 'badfish'...
remote: Enumerating objects: 1698, done.
remote: Counting objects: 100% (627/627), done.
remote: Compressing objects: 100% (422/422), done.
remote: Total 1698 (delta 341), reused 387 (delta 173), pack-reused 1071
Receiving objects: 100% (1698/1698), 487.17 KiB | 1.32 MiB/s, done.
Resolving deltas: 100% (892/892), done.
t14:/tmp/badfish$ cd badfish/
t14:/tmp/badfish/badfish (master)$ ls
config  CONTRIBUTING.md  Dockerfile  Dockerfile_dev  image  LICENSE  README.md  requirements.txt  rpm  setup.py  src  tests  tox.ini
t14:/tmp/badfish/badfish (master)$ src/badfish/badfish.py -u quads -p <redacted> -i config/idrac_interfaces.yml -H mgmt-e22-h12-b04-fc640.rdu2.scalelab.redhat.com -t director
- ERROR    - Couldn't find a valid key defined on the interfaces yaml: uefi_fc640_b04_interfaces
```

**Comment by sadsfae** [comment]
Can confirm that the `uefi_*` key/value pairs in `idrac_interfaces.yml` seem to trigger this.  Issue is likely due to some parsing/matching there of some kind.  A workaround is to just comment out those from the config file since the EFI features to my knowledge are not being used yet.
