### ISSUE TITLE
unable to set boot mode to uefi on 740xd's

### ISSUE THREAD

**Issue by asyedham** [redhat-performance/badfish#245]
I tried setting the boot mode to uefi but it fails with boot mode not found
(.venv) [asyedham@perfc-360g8-04 badfish]$         python3 badfish.py -H mgmt-e24-h37-740xd -u $user -p $password  --set-bios-attribute --attribute Bootmode --value Uefi
- WARNING  - Could not retrieve Bios Attributes.
- ERROR    - Bootmode not found. Please check attribute name.
- ERROR    - Attribute not found

**Comment by grafuls** [comment]
@asyedham The attribute name is a case sensitive field and while you correctly followed the instructions on the README, the actual name for that is BootMode.
We have now amended the documentation with the proper casing.
