### ISSUE TITLE
[RFE] Allow formatting output to JSON or YAML

### ISSUE THREAD

**Issue by EliadCohen** [redhat-performance/badfish#250]
**Is your feature request related to a problem? Please describe.**
I think it could be useful to receive a structured output that can play nice with other tools

**What System / IPMI Platform?**
Multiple different systems but would like to use Badfish with Ansible to query and set attributes of *any* system

**Describe the Possible Solution**
Add a cli flag --output-format that is set with JSON/YAML or what you want to name the current format
Could also be nice if only the value of one of the fields can be returned.
There's something along those lines in the openstack tripleo python client.

**Describe alternatives you've considered**
A combination of awk and grep in an ansible task running a simple shell block

**Additional Info**
I think this can be a nice first issue
I also think the tool rocks, thank you!

**Comment by sadsfae** [comment]
@EliadCohen this is a really great RFE, thanks for filing it.  We're looking into this.
