### ISSUE TITLE
Add a retry mode for command execution

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#3]
This is an RFE for providing a retry mode argparse option.  What this would look like is a `-r` or `--retry` flag that leverages the exit status of the command/action and retries until it succeeds.

By default badfish should just run once, but if `-r` or `--retry` is specified it will try either 10 times or until it succeeds then quit.

```
badfish.py -H mgmt-yourhost.com -u root -p password -i config/drac_interfaces.yml -t foreman --pxe --retry
```

- There should be a sane default for retries (10?) before failing completely (we don't want it running forever)
- There should be a sane default for timeout between tries (10 seconds?)
- Number of retries should be configurable e.g. `--retry 20` with a reasonable default substituted if not specified.

**Why Is this Needed?**

We want to replace our legacy Ansible playbooks that manage Dell interface boot order with badfish.  This change is recommended for this.  It will also let people use badfish in a more automated/utility fashion.

**Comment by grafuls** [comment]
This has been addressed on:
