### ISSUE TITLE
Issues with module paths while using the badfish.py script

### ISSUE THREAD

**Issue by sanjaychari** [redhat-performance/badfish#301]
**Your System Details**

* Python Version: Python 3.6.8
* Operating System: RHEL 7.8
* Target System Type: Dell

**Describe the bug**
We use the badfish.py script to execute badfish commands. While running the following command https://github.com/redhat-performance/jetpack/blob/d7567b4294ba6efb17a68d33f9ae3974436d140e/tasks/install_os.yml#L78, the following error occured.

File \"badfish.py\", line 24, in <module>\n    from src.badfish.helpers.async_lru import alru_cache\nModuleNotFoundError: No module named 'src'", 
    "stderr_lines": [
        "Traceback (most recent call last):", 
        "  File \"badfish.py\", line 24, in <module>", 
        "    from src.badfish.helpers.async_lru import alru_cache", 
        "ModuleNotFoundError: No module named 'src'"

I think the error is related to the module path, as changing that line to the one below seems to fix the issue.
from helpers.async_lru import alru_cache

**To Reproduce / What were you Doing?**
Run a command similar to https://github.com/redhat-performance/jetpack/blob/d7567b4294ba6efb17a68d33f9ae3974436d140e/tasks/install_os.yml#L78.

**Expected Behavior**
https://github.com/redhat-performance/jetpack/blob/d7567b4294ba6efb17a68d33f9ae3974436d140e/tasks/install_os.yml#L78 should work without issues.

**Comment by sadsfae** [comment]
Thanks for filing this, we're looking into it.  We think it may have to do with some import changes required to build the automated COPR RPM.

**Comment by sanjaychari** [comment]
@grafuls 

We started installing badfish with `pip install -e` in [November](https://github.com/redhat-performance/jetpack/pull/420) last year as a workaround for a similar issue with badfish, around the same time that [Jetski](https://github.com/redhat-performance/JetSki/issues/186#issuecomment-982666646) was facing issues too. Thanks for the PYTHONPATH suggestion. We will try that out.

**Comment by sanjaychari** [comment]
@grafuls @sadsfae 
I am facing this same issue again while using version 1.0.2 of the badfish CLI standalone(not using Jetpack).
```

(base) [schari@schari badfish]$ badfish -H mgmt-f03-h10-000-r640.rdu2.scalelab.redhat.com -u quads -p rdu2@1838 -i config/idrac_interfaces.yml -t foreman
Traceback (most recent call last):
  File "/usr/bin/badfish", line 11, in <module>
    load_entry_point('badfish==1.0.2', 'console_scripts', 'badfish')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/badfish/badfish.py", line 24, in <module>
    from src.badfish.helpers.async_lru import alru_cache
ModuleNotFoundError: No module named 'src'
```

**Comment by grafuls** [comment]
@sanjaychari What install method did you use for that?

**Comment by sanjaychari** [comment]
@grafuls I had installed the CLI from the COPR repository earlier.
```
dnf copr enable quadsdev/python3-badfish  -y
dnf install python3-badfish -y
```
I updated the badfish cli to the latest version recently, and this issue appeared after that.

**Comment by mordechai** [comment]
@grafuls  any updates on this issue?  or suggested work arounds?

**Comment by sadsfae** [comment]
@mordechai @sanjaychari we have a fix being merged for this shortly within the hour.

**Comment by sadsfae** [comment]
@sanjaychari @mordechai please note that `src/badfish/badfish.py` has been renamed to `src/badfish/main.py`
