### ISSUE TITLE
Badfish Container fails to execute bulk actions

### ISSUE THREAD

**Issue by rajeshP524** [redhat-performance/badfish#320]
After one of the recent commits[1] in badfish, getting an error while executing bulk actions using badfish container.
[1] https://github.com/redhat-performance/badfish/pull/308

**Here is how the error looks like:**
$ sudo podman run -it -v `dir_path_to_host_list`:/dell --rm quay.io/quads/badfish --host-list /dell/dell-hosts -u `username` -p `password` -i config/idrac_interfaces.yml -t foreman --pxe

`Traceback (most recent call last):`
  `File "/usr/local/bin/badfish", line 8, in <module>`
  `  sys.exit(main())`
  `File "/usr/local/lib/python3.9/site-packages/src/badfish/main.py", line 2399, in main`
  `  bfh_output = bfl.badfish_handler.output(`
  `File "/usr/local/lib/python3.9/site-packages/src/badfish/helpers/logger.py", line 132, in output`
  `  for x in sorted(`
  `File "/usr/local/lib/python3.9/site-packages/src/badfish/helpers/logger.py", line 133, in <lambda>`
   ` self.formatted_msg, key=lambda y: host_order[y.split()[0][1:-1]]`
`KeyError: 'src.badfish.helpers.logger'`

**Here is the format of host-list file:**
   hostname-1
   hostname-2
   hostname-3

**Comment by grafuls** [comment]
Tried running this locally and even though I didn't get an error I can see the host_order includes the `logger` which I think might be causing this issue when running via `podman`.

```
~/Sources/badfish-mine   development ±  PYTHONPATH=/home/grafuls/Sources/badfish-mine/ python3 src/badfish/main.py --host-list /tmp/dell-hosts -u {USER} -p {PASS} -i config/idrac_interfaces.yml --power-state
> /home/grafuls/Sources/badfish-mine/src/badfish/helpers/logger.py(131)output()
    130                 import ipdb; ipdb.set_trace()
--> 131                 sorted_msg = [
    132                     x

ipdb> l
    126                 Dumper=NoAliasDumper,
    127             )
    128         else:
    129             if len(host_order) > 2:
    130                 import ipdb; ipdb.set_trace()
--> 131                 sorted_msg = [
    132                     x
    133                     for x in sorted(
    134                         self.formatted_msg, key=lambda y: host_order[y.split()[0][1:-1]]
    135                     )
    136                 ]

ipdb> host_order
{'src.badfish.helpers.logger': 9223372036854775807, 'mgmt-e25-h33-740xd': 0, 'mgmt-e25-h27-740xd': 1}
```
