### ISSUE TITLE
[RFE] Lifecycle controller removal

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/badfish#365]
**Is your feature request related to a problem? Please describe.**
Whenever we run `change_boot_order` we subsequently call `create_bios_config_job` which creates a job for the bios configuration change to be controlled by the lifecycle controller where it's main purpose is to have visibility on the progress of 
multiple long running task. In the case that there is an existing job runnnig that wasn't completed yet, `redfish` will return an error creating the bios config job and the whole process will fail.

The execution of a bios config job will occur at reboot, regardless of the bios config job being created, so there is no real impetus in having the lifecycle controller running the bios config change for a simple task as `change_boot_order` and we can make `badfish` less error prone if we avoid creating the config job and issue a reboot right after.

**What System / IPMI Platform?**
DELL

**Describe the Possible Solution**
Remove the calls to `create_bios_config_job`.

**Additional Info**
This is a conceptual enhancement and should be thoroughly tested.

**Comment by k3nd1k** [comment]
I am not sure if the `create_bios_config_job` function should be removed/is not needed. 😅
Investigated it a bit and here is what I got 🕵️‍♂️:

- I picked the change_boot functionality for testing it. (Was monitoring the behavior through virtual console.)

- Here is how it works with the `create_bios_config_job` **still in place**:
	- First I set the boot to `director` type as a starting point.
	- Then I run the command to change it to `foreman`, which it did.
	- After it was done, I ran the command to change boot to `foreman` *again*, and it didn't go through because it said that it's already in that config. This was expected and worked like it should.

- Now I went and **removed the call** to `create_bios_config_job` from the `change_boot` function and tried to do this again:
	- Changed the boot to `director`, went through.
	- Then changed the boot to `foreman`, went through, all good.
	- Ran it again to set the boot to `foreman`, but got no message saying it is in that config now, and the command went trough, restarted the server and just executed all of itself again.
 
From seeing this behavior I don't think the call to create_bios_config_job is there without it's purpose as the command clearly works differently when that function is used compared to when not. The settings may not actually apply without it, or they might not be surviving a reboot.

**Comment by grafuls** [comment]
Based on: [dell-racadm-bios-nic-techsheet.pdf](https://raw.githubusercontent.com/wiki/radiasoft/devops/manuals/dell-racadm-bios-nic-techsheet.pdf)
Seems like what it would be optional for creating the job is actually the reboot job.
Closing issue as won't resolve.
