### ISSUE TITLE
Traceback when using get-power-consumed

### ISSUE THREAD

**Issue by jmencak** [redhat-performance/badfish#388]
**Your System Details**
Fedora 38

* Python Version:
Python 3.11.6

* Operating System:
Linux

* Target System Type: (_e.g. Dell, SuperMicro_)
Dell r740

* IPMI / Out-of-band Firmware Version: (_e.g. iDRAC 8 2.60.60.60)
iDRAC Firmware Version 4.22.00.00

**Describe the bug**
```
+ badfish -H mgmt-e25-h19-740xd.alias.bos.scalelab.redhat.com -u <user> -p <pass> --get-power-consumed
Traceback (most recent call last):
  File "/usr/bin/badfish", line 33, in <module>
    sys.exit(load_entry_point('badfish==1.0.2', 'console_scripts', 'badfish')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/badfish/main.py", line 2701, in main
    _host, result = loop.run_until_complete(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/badfish/main.py", line 2300, in execute_badfish
    await badfish.get_power_consumed_watts()
  File "/usr/lib/python3.11/site-packages/badfish/main.py", line 652, in get_power_consumed_watts
    self.logger.info(f"Current watts consumed: {data['PowerControl'][0]['PowerConsumedWatts']}")
                                                ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**To Reproduce / What were you Doing?**
```
badfish -H mgmt-e25-h19-740xd.alias.bos.scalelab.redhat.com -u <user> -p <pass> --get-power-consumed
```

**Expected Behavior**
No traceback

**Comment by grafuls** [comment]
Thanks for pointing this one out Jiri. 
This is usually caused by the PowerControl not being captured correctly by redfish.
I believe you could work around the issue by resetting iDrac running `--racreset`.
Will leave the issue open to return a more user friendly error message suggesting the `--racreset`.

**Comment by jmencak** [comment]
Thank you for a quick response. I can confirm that resetting iDRAC helped.  While it would be nice to have a better message from badfish about this (perhaps a suggestion to reset iDRAC), closing this issue.
/close
