### ISSUE TITLE
--reboot-only reboots, twice

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/badfish#40]
I tried this while watching the DRAC console:

```
[bengland@bene-laptop badfish]$ ./badfish.py -H mgmt-e23-h31-740xd -u quads -p 492728 -i config/idrac_interfaces.yml --reboot-only
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- INFO     - Command passed to GracefulRestart server, code return is 204.
- INFO     - Polling for host state: Off
  Polling: [>                   ] 0% - Host state: On  
  Polling: [>                   ] 7% - Host state: On  
  Polling: [-->                 ] 13% - Host state: On  
  Polling: [--->                ] 20% - Host state: On  
  Polling: [---->               ] 27% - Host state: On  
  Polling: [------>             ] 33% - Host state: On  
  Polling: [------->            ] 40% - Host state: On  
  Polling: [-------->           ] 47% - Host state: On  
  Polling: [---------->         ] 53% - Host state: On  
  Polling: [----------->        ] 60% - Host state: On  
  Polling: [------------>       ] 67% - Host state: On  
  Polling: [-------------->     ] 73% - Host state: On  
  Polling: [--------------->    ] 80% - Host state: On  
  Polling: [---------------->   ] 87% - Host state: On  
  Polling: [------------------> ] 93% - Host state: On  
- WARNING  - Unable to graceful shutdown the server, will perform forced shutdown now.
```
<at this point the server had already rebooted, and this forced a 2nd reboot>
```
- INFO     - Command passed to ForceOff server, code return is 204.
- INFO     - Polling for host state: Not Down
  Polling: [------------------->] 100% - Host state: Off
- INFO     - Command passed to On server, code return is 204.
```
Why did badfish.py conclude that the server hadn't rebooted?

**Comment by bengland2** [comment]
It's reproducible, server was completely rebooted when badfish.py gave up and did a power cycle!    I ran this from both my laptop at home and from e23-h29-740xd in the same rack so it's not a network issue.   

My suggestion is to not force a power cycle unless a user specifically requests it, with --power-cycle option that doesn't exist yet.    This is *very bad* because power cycling puts extra wear and tear on the hardware, you don't want to do it to 600 machines in the scale lab and Alias all the time.    How many times will a power reset not work but power-cycle will work?   What you might want to do is have default be "graceful reset", and provide an option for non-graceful reset  or power-cycle if the user requests that.

Also, the progress bar is really a timeout bar, since it does not correspond at all to the progress of the system in rebooting.   You should call it that so people don't get confused about what they are seeing.

I think the problem here is in reboot_server() where it polls for host state "Off".    If it enters this state, it does not stay there for very long, when you do a system reset.    In this Alias lab Dell 740XD, e23-h31-740xd, I never saw the server in the off state.  Why poll for 75 seconds before concluding that your reset failed?   And how do you know that you'll actually be able to observe the system in a state other than "On"?   How timing-dependent is this test?  how independent of hardware model is it?

BTW I'm a big fan of this tool.

**Comment by sadsfae** [comment]
I can confirm this happens also from recent testing.
