### ISSUE TITLE
[RFE] Support Performance Lab boot order configuration

### ISSUE THREAD

**Issue by akrzos** [redhat-performance/badfish#404]
Currently the scale lab and performance lab have different idrac boot order devices, badfish should include a configuration for both labs since it is advertised as the tool to rebuild and reconfigure the boot order for performance lab machines. I found this while working on r750 machines.

```console
$ badfish -H mgmt-cc37-h27-000-r750.xxxx -u quads -p xxxxx  -i config/idrac_interfaces.yml -t foreman
- INFO     - Job queue for iDRAC mgmt-cc37-h27-000-r750.rdu3.example.com successfully cleared.
- WARNING  - Some interfaces are not valid boot devices. Ignoring: NIC.Integrated.1-1-1
- INFO     - Command passed to ForceOff server, code return is 204.
- INFO     - Polling for host state: Not Down
- POLLING: [------------------->] 100% - Host state: On  
- INFO     - Command passed to On server, code return is 204.
```

**Comment by sadsfae** [comment]
@akrzos thanks for filing this, until recently I'm not sure we knew what those interface names were.  You're probably aware of this but you can always craft and map your own `idrac_interfaces.yml` file in lieu of having this in the repository for you until new machine types get added (or if there are deviations needed) so nobody should ever be blocked on this.

https://github.com/redhat-performance/badfish?tab=readme-ov-file#host-type-overrides

**Comment by sadsfae** [comment]
After some discussion it's a good idea to split out `idrac_interfaces.yml` templates per environment.  Going forward after some healthy notice we will likely also remove them and replace with a generic example configuration and instead let internal tenants pull them from internal Gitlab.  As this is a code repository and not really that well-purposed for housing changing configuration files this seems like a better fit.

Soon we'll have these boot interface overrides in place however and they'll likely be one of the last ones we bake into the container and RPM/repo in lieu of the aforementioned changes when that happens.   cc: @grafuls

**Comment by akrzos** [comment]
@sadsfae and @grafuls Thanks for taking a look and addressing.
