### ISSUE TITLE
idrac_interfaces.yml doesn't parse

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/badfish#41]
When I try to adjust the boot order using syntax given in README.md, it fails with a parse error:

```
# ./badfish.py -H mgmt-e24-h33-740xd -u quads -p 492728 -i config/idrac_interfaces.yml -t director --verbose
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- DEBUG    - Getting bios boot mode.
Traceback (most recent call last):
  File "./badfish.py", line 806, in <module>
    sys.exit(main())
  File "./badfish.py", line 800, in main
    execute_badfish(host, args, logger)
  File "./badfish.py", line 741, in execute_badfish
    badfish.change_boot(host_type, interfaces_path, pxe)
  File "./badfish.py", line 301, in change_boot
    _type = self.get_host_type(interfaces_path)
  File "./badfish.py", line 210, in get_host_type
    interfaces[_host] = definitions["%s_%s_interfaces" % (_host, host_model)].split(",")
KeyError: 'foreman_740xd_interfaces'
```
I think it's not parsing idrac_interfaces.yml but not sure yet.

**Comment by bengland2** [comment]
the problem with Alias is that the host names are all of form rack-host-model and the model is "740xd", but in idrac_interfaces.yml it's "r740xd".    in this case maybe we need an alias version of idrac_interfaces.yml.

However, I tried to toggle between -t director and -t foreman and it failed.  Here's my idrac_interfaces.yml subset relevant to "740xd" model:

```
director_740xd_interfaces: NIC.Slot.2-2-1,NIC.Integrated.1-3-1,HardDisk.List.1-1
foreman_740xd_interfaces: NIC.Integrated.1-3-1,HardDisk.List.1-1,NIC.Integrated.1-1-1
```
And when I try to toggle these very different modes, it does not work:
```
[bengland@bene-laptop badfish]$ ./badfish.py -H mgmt-e24-h33-740xd -u quads -p 492728 -i config/idrac_interfaces.yml -t director
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- WARNING  - No changes were made since the boot order already matches the requested.
[bengland@bene-laptop badfish]$ ./badfish.py -H mgmt-e24-h33-740xd -u quads -p 492728 -i config/idrac_interfaces.yml -t foreman
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- WARNING  - No changes were made since the boot order already matches the requested.
```
Clearly the boot order can't match both of these!

**Comment by sadsfae** [comment]
We'll find a fix for this without breaking any FQDN matching, for now consider the shipped `idrac_interfaces.yml` an example - you should modify it locally if you need to, it looks like some naming conventions between labs do not line up.

**Comment by bengland2** [comment]
I pulled latest badfish, applied this change to idrac_interfaces.yml:
```
-director_r740xd_interfaces: NIC.Integrated.1-1-1,HardDisk.List.1-1,NIC.Integrated.1-3-1
+director_r740xd_interfaces: NIC.Slot.2-1,HardDisk.List.1-1,NIC.Integrated.1-3-1
```
And tried it again in Alias:
```
[bengland@bene-laptop badfish]$ ./badfish.py -H mgmt-e23-h23-740xd -u quads -p 494292 -i config/idrac_interfaces.yml -t director
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
Traceback (most recent call last):
  File "./badfish.py", line 806, in <module>
    sys.exit(main())
  File "./badfish.py", line 800, in main
    execute_badfish(host, args, logger)
  File "./badfish.py", line 741, in execute_badfish
    badfish.change_boot(host_type, interfaces_path, pxe)
  File "./badfish.py", line 301, in change_boot
    _type = self.get_host_type(interfaces_path)
  File "./badfish.py", line 210, in get_host_type
    interfaces[_host] = definitions["%s_%s_interfaces" % (_host, host_model)].split(",")
KeyError: 'foreman_740xd_interfaces'
```
I then tried changing the key to 'director_740xd_interfaces' but this did not work either, same KeyError.   I thought the above commit was supposed to handle this.  What change would you make to idrac_interfaces to get this to work?

**Comment by grafuls** [comment]
The latest changes to idrac interfaces yaml file should resolve this. We are not making use of the prefix 'r' for the model number anymore on the host name.

**Comment by QuantumPosix** [comment]
To me it looks like you are specifying a slot that does not exist on these
systems as to why it says it can not change the order to that:
racadm get NIC.NICConfig
NIC.NICConfig.1 [Key=NIC.Integrated.1-1-1#NICConfig]
NIC.NICConfig.2 [Key=NIC.Integrated.1-2-1#NICConfig]
NIC.NICConfig.3 [Key=NIC.Integrated.1-3-1#NICConfig]
NIC.NICConfig.4 [Key=NIC.Integrated.1-4-1#NICConfig]
NIC.NICConfig.5 [Key=NIC.Slot.7-1-1#NICConfig]
NIC.NICConfig.6 [Key=NIC.Slot.7-2-1#NICConfig]
~ Thanks,

Chris
978.392.1043
