### ISSUE TITLE
badfish.py doesn't clear job queue

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/badfish#45]
I can't seem to clear the job queue with either badfish or DRAC GUI, this is preventing me from changing the boot order.
```
[bengland@bene-laptop badfish]$ ./badfish.py -H mgmt-e23-h23-740xd -u quads -p 494292 -i config/idrac_interfaces.yml --clear-jobs
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- WARNING  - iDRAC version installed does not support DellJobService
- WARNING  - Clearing job queue for job IDs: ['JID_640133055279'].
- ERROR    - Job queue not cleared, current job queue contains jobs: ['JID_640133055279'].
```

**Comment by bengland2** [comment]
Chris Enright seems to know why this happens, apparently JID_CLEARALL doesn't work on 740xd? @QuantumPosix ?

**Comment by QuantumPosix** [comment]
I am testing this now, it did not earlier while a job was there, and took a
"jobqueue delete --all" instead of "jobqueue delete -i JID_CLEARALL". I
will be testing further on a node that is not involved in any reservations.
~ Thanks,

Chris
978.392.1043

**Comment by QuantumPosix** [comment]
So it looks like a firmware update for iDrac9 will fix the issue as annotated below: 
    Old iDrac Firmware(3.21.21.21):
    ./badfish.py -H $host -u root -p "calvin" --clear-jobs
    - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
    - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
    - WARNING  - iDRAC version installed does not support DellJobService
    - WARNING  - Clearing job queue for job IDs: ['JID_641574909915'].
    - ERROR    - Job queue not cleared, current job queue contains jobs: ['JID_641574909915'].
     
    New iDrac Firmware(3.34.34.34):
    ./badfish.py -H $host -u root -p "calvin" --clear-jobs
    - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
    - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
    - INFO     - Job queue for iDRAC $host successfully cleared.
     
    Same job in the queue - seems to be a minimum iDrac version required for iDrac9 machines as well. I will start updating the firmware on the hosts.

**Comment by grafuls** [comment]
> So it looks like a firmware update for iDrac9 will fix the issue as annotated below:
> 
> Old iDrac Firmware(3.21.21.21):
> 
> ```
> ./badfish.py -H $host -u root -p "calvin" --clear-jobs
>   - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
>   - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
>   - WARNING  - iDRAC version installed does not support DellJobService
>   - WARNING  - Clearing job queue for job IDs: ['JID_641574909915'].
>   - ERROR    - Job queue not cleared, current job queue contains jobs: ['JID_641574909915'].
>    
> ```
> 
> New iDrac Firmware(3.34.34.34):
> 
> ```
> ./badfish.py -H $host -u root -p "calvin" --clear-jobs
>  - INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
>  - INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
>  - INFO     - Job queue for iDRAC $host successfully cleared.
> ```
> 
> ```
> Same job in the queue - seems to be a minimum iDrac version required for iDrac9 machines as well. I will start updating the firmware on the hosts. 
> ```

Closing as per last findings from @QuantumPosix.
