### ISSUE TITLE
[RFE]  Add capability to add NIC port PxE setting to enabled (solo or based on idrac_interfaces.yml) 

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/badfish#49]
Ideally having the ability to set a new NIC interface from a non PxE enabled to PxE enabled both by itself and in the condition of reading the idrac_interfaces.yml. up for ideas for a --set-pxe true/false --pxe-nic $nic.

**Comment by sadsfae** [comment]
This could be accomplished by modeling the same batch / job workflow we use for boot order changes.

@QuantumPosix can you paste us the sanitized racadm equivalent command you currently use for this?

**Comment by QuantumPosix** [comment]
looking to add in functionality of Redfish API to set a nic to pxe (if not enabled) and to unset it (and set a default setup to pxe) 
Get a list of installed nics:
`get nic.nicconfig`

```
racadm get nic.niCconfig 
NIC.niCconfig.1 [Key=NIC.Integrated.1-1-1#niCconfig]
NIC.niCconfig.2 [Key=NIC.Integrated.1-2-1#niCconfig]
NIC.niCconfig.3 [Key=NIC.Integrated.1-3-1#niCconfig]
NIC.niCconfig.4 [Key=NIC.Integrated.1-4-1#niCconfig]
NIC.niCconfig.5 [Key=NIC.Slot.7-1-1#niCconfig]
NIC.niCconfig.6 [Key=NIC.Slot.7-2-1#niCconfig]
```

Choose the nic to set to PXE (number corresponds to nic above):
`set nic.nicconfig.5.legacybootproto PXE`

```
racadm set nic.nicconfig.5.legacybootproto PXE 
[Key=NIC.Slot.7-1-1#legacybootproto]
RAC1017: Successfully modified the object value and the change is in 
       pending state.
       To apply modified value, create a configuration job and reboot 
       the system. To create the commit and reboot jobs, use "jobqueue" 
       command. For more information about the "jobqueue" command, see RACADM 
       help.
```
Schedule the job to run and reboot at the same time:
`jobqueue create NIC.Slot.7-1-1 -r pwrcycle -s TIME_NOW -e TIME_NA`

```
racadm jobqueue create NIC.Slot.7-1-1  -r pwrcycle -s TIME_NOW -e TIME_NA  
RAC1024: Successfully scheduled a job.
Verify the job status using "racadm jobqueue view -i JID_xxxxx" command.
Commit JID = JID_646971984878
Reboot JID = RID_646971985077
```

**Comment by bengland2** [comment]
this would have helped me resolve[ issue 119](https://github.com/redhat-performance/badfish/issues/119)  faster

**Comment by grafuls** [comment]
This is now possible with the new --set-bios-attribute functionality as per below:

**~/badfish   development  ./src/badfish/badfish.py -H mgmt-{HOST} -u root -p {PASS} --set-bios-attribute --attribute BootMode --value Uefi**
\- INFO     - Command passed to set BIOS attribute pending values.
\- INFO     - Command passed to ForceRestart server, code return is 204.
\- INFO     - Polling for host state: Not Down
\- POLLING: [------------------->] 100% - Host state: On  
\- WARNING  - Command failed to On server, host appears to be already in that state.

**~/badfish   development  ./src/badfish/badfish.py -H mgmt-{HOST} -u root -p {PASS} --check-boot**         
\- INFO     - Current boot order:
\- INFO     - 1: NIC.PxeDevice.1-1

**~/badfish   development  ./src/badfish/badfish.py -H mgmt-{HOST} -u root -p {PASS} --set-bios-attribute --attribute PxeDev2EnDis --value Enabled**
\- INFO     - Command passed to set BIOS attribute pending values.
\- INFO     - Command passed to ForceRestart server, code return is 204.
\- INFO     - Polling for host state: Not Down
\- POLLING: [------------------->] 100% - Host state: On  
\- WARNING  - Command failed to On server, host appears to be already in that state.

**~/badfish   development  ./src/badfish/badfish.py -H mgmt-{HOST} -u root -p {PASS} --check-boot**
\- INFO     - Current boot order:
\- INFO     - 1: NIC.PxeDevice.1-1
\- INFO     - 2: NIC.PxeDevice.2-1

NOTE: this is only possible when the BootMode is set to Uefi.
