### ISSUE TITLE
expand --pxe one shot boot functionality

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#5]
We need to do some further testing / fixes on the `--pxe` option, it shouldn't necessarily need to have a corresponding `-t foreman/director` argparse unless we want to tell it to one-shot boot off that particular interface.

This may be useful however to others.  This issue covers the following changes:

- make `--pxe` work without needing `-t` (default to foreman interface)
- if `-t director` or `-t foreman` is passed along with config file one-shot boot off that interface instead

**Comment by grafuls** [comment]
Removed the "required=true" setting for this 2 on: https://github.com/redhat-performance/badfish/commit/33f19f9861ddd96cf3adecbeb5c65be825130d91
