### ISSUE TITLE
[Bug]GracefulRestart not a valid option for G14 Dells

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/badfish#66]
Python Version:
    Operating System: Fedora 30
    Target System Type: Generation 14 Dell's
    IPMI / Out-of-band Firmware Version: 3.34.34.34

Currently a GracefulRestart is called during quads move and rebuild. This is not a valid call as an option:
curl -k --user "username:password" -H "Content-Type: application/json" https://mgmt-host/redfish/v1/Systems/System.Embedded.1 | python -m json.tool | grep -A7 ResetType
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 7607 100 7607 0 0 22307 0 --:--:-- --:--:-- --:--:-- 22242
"ResetType@Redfish.AllowableValues": [
"On",
"ForceOff",
"ForceRestart",
"GracefulShutdown",
"PushPowerButton",
"Nmi"
],
Need to adjust for new generation redfish calls.

**Comment by sadsfae** [comment]
This is fixed in the `badfish` QUADS library here:

https://github.com/redhat-performance/quads/commit/acda6ea0a80bcaa72266c81c205e81a8950cd2fd

Looks like this still needs to be moved into standalone/upstream badfish.
