### ISSUE TITLE
Provide better logging verbosity when -t idrac_interfaces.yml not passed

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#76]
**Your System Details**

* Python Version: `3.7.6`
* Operating System: `Fedora 30`
* Target System Type: `Dell r630`
* IPMI / Out-of-band Firmware Version: `iDrac8 63.60.60.60`

**Describe the bug**
Getting a traceback running latest master branch badfish when running `--boot-to-type foreman`

I am running this via `python3 badfish.py -H mgmt-$host -u user -p pass --boot-to-type foreman`

I also get this via a container also.

Additionally, it seems that for the r630 systems `--boot-to` is not issuing a reboot.

```
- INFO     - Systems service: /redfish/v1/Systems/System.Embedded.1.
- INFO     - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
Traceback (most recent call last):
  File "badfish.py", line 940, in <module>
    sys.exit(main())
  File "badfish.py", line 934, in main
    execute_badfish(host, args, logger)
  File "badfish.py", line 853, in execute_badfish
    badfish.boot_to_type(boot_to_type, interfaces_path)
  File "badfish.py", line 632, in boot_to_type
    self.boot_to(device)
  File "badfish.py", line 608, in boot_to
    if self.check_device(device):
  File "badfish.py", line 701, in check_device
    if device.lower() in boot_devices:
AttributeError: 'NoneType' object has no attribute 'lower'
```

Seems to be from the use of `.lower` here:

https://github.com/redhat-performance/badfish/blob/master/badfish.py#L701

**UPDATE**

It appears I was not passing `-i idrac_interfaces.yml` and this is user error.  We'll leave this open anyway and implement more verbose logging to tell people like me to stop being boneheads and use the interfaces file so it can consult the key/value pairs it needs to complete.

**Comment by grafuls** [comment]
This has already been resolved on a previous patch.
`src/badfish/badfish.py -H mgmt-host.com -u root -p {PASS} -t foreman                                 
- ERROR    - You must provide a path to the interfaces yaml via `-i` optional argument.
- ERROR    - There was something wrong executing Badfish.`
