### ISSUE TITLE
idrac_interfaces.yml has wrong boot order

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/badfish#92]
**Your System Details**
alias cloud02
* Python Version: 3
* Operating System: RHEL8/CoreOS
* Target System Type: (_e.g. Dell, SuperMicro_) Dell 740xd
* IPMI / Out-of-band Firmware Version: (_e.g. iDRAC 8 2.60.60.60) 

**Describe the bug**

I tried to run [Dustin Black's playbook](https://github.com/dustinblack/baremetal-deploy.git) and it fails ([log here](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/ocp4/ipi/03-17-14-50.log)).   In progress of troubleshooting, I realized that the "director" interface that I was supposed to use was "eno1", but I was using ens7f0.    But this means I can't use the 25-GbE interface for provisioning network, and I can't use both 25-GbE NIC ports.   @dustinblack  thought this was wrong, that "director_740xd_interfaces" should have the Foreman interface "eno3" last, so that any of the other NIC ports could PXE boot, right Dustin?   This would give us maximum flexibility.   But what it does in [director_740_interfaces record](https://github.com/redhat-performance/badfish/blob/master/config/idrac_interfaces.yml#L16) is make the Foreman interface 2nd, after eno1 interface.  When PXE boot gets to the Foreman interface, Foreman will tell it to boot from local drive, so subsequent interfaces will not get used.   so the only other interface that we can use for PXE boot is eno1, which is the 10-GbE interface in Alias.   If my understanding of the PXE boot sequence is correct, can we please change this?

 
**To Reproduce / What were you Doing?**
1. See [Dustin Black's IPI directions here](https://docs.google.com/document/d/1hl2qVWyRjqhKT3ZR5Q2xn9Ip1DLShanxQcnp11Zf1tw/edit#heading=h.89fh1zoxpvw4)
2. edit inventory/hosts [as shown here](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/ocp4/ipi/hosts)

**Comment by QuantumPosix** [comment]
The suggestion is to put in the following line for director - this has no conflicts with anything else (all high speed interfaces first, then foreman, then hard disk):
director_740xd_interfaces: NIC.Integrated.1-1-1,NIC.Integrated.1-2-1,NIC.Slot.7-1-1,NIC.Slot.7-2-1,NIC.Integrated.1-3-1,HardDisk.List.1-1

**Comment by bengland2** [comment]
Nitpick: It's not really necessary IMO to include both NIC.Slot.7-1-1 and 7-2-1, since they are equivalent, either one of them would do (as long as we are consistent), and having just 1 of them reduces the time spent timing out PXE boot interfaces.   The reasoning here is the same as why we don't include eno2=NIC.Integrated.1.2.1 in the list.   but I don't want that to get in the way of progress.   Because eliminating need for a boot order change would significantly reduce time and complexity of an OCP4 UPI install in Alias.   Would nodes arrive at a reservation with -t director set?   e-mail from @sadsfae (Will) earlier e-mail seemed to suggest this.

**Comment by sadsfae** [comment]
@QuantumPosix has resolved this with https://github.com/redhat-performance/badfish/pull/94.

Additionally a new badfish docker image is built with these changes so you'll want to `docker pull quads:latest` or the podman equivalent.
